# Generated by Django 5.2.1 on 2025-05-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_auth', '0002_patient_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.TextField(unique=True),
        ),
    ]
